#!/usr/bin/env python3
"""Curated UK vehicle-family art direction for the complete v2 fleet.

This module is deliberately release-neutral.  It describes what each logical
MissionChief slot must look like; release profiles decide which 200 px master
currently fulfils that brief.
"""

from __future__ import annotations


SCHEMA_VERSION = 1


FAMILIES: dict[str, dict] = {
    "forward-control-fire": {
        "name": "British forward-control fire appliance",
        "visual_lineage": "Modern UK urban pump proportions on a logo-free cab-over chassis.",
        "propulsion": "self-propelled-road",
        "reference_asset": "fire-rescue-pump",
        "minimum_master_bbox": [150, 105],
        "minimum_reference_similarity": 0.82,
        "required_cues": [
            "forward-control cab with divided windscreen",
            "front wheel and cab separated from the equipment body",
            "roller-shutter lockers with a readable pump-body rhythm",
            "roof ladder or gantry equipment",
            "UK high-visibility blocks and rear chevrons without protected marks",
        ],
    },
    "specialist-emergency-hgv": {
        "name": "British specialist emergency HGV",
        "visual_lineage": "Purpose-built UK heavy response chassis with a role-specific modular body.",
        "propulsion": "self-propelled-road",
        "reference_asset": "rescue-support-unit",
        "minimum_master_bbox": [150, 80],
        "minimum_reference_similarity": 0.78,
        "required_cues": [
            "complete powered cab and visible glazing",
            "heavy chassis with grounded wheel groups",
            "role-specific tank, locker, command or support body",
            "roofline equipment appropriate to the task",
            "service-correct UK high-visibility treatment",
        ],
    },
    "aerial-fire": {
        "name": "British aerial fire appliance",
        "visual_lineage": "Multi-axle UK aerial platform with an unmistakable boom and stabiliser system.",
        "propulsion": "self-propelled-road",
        "reference_asset": "aerial-appliance",
        "minimum_master_bbox": [175, 105],
        "minimum_reference_similarity": 0.90,
        "required_cues": [
            "forward-control crew cab",
            "long multi-axle chassis",
            "telescopic boom or ladder pack",
            "turntable and stabiliser hardware",
            "front wheel, windscreen and front-end structure",
        ],
    },
    "hooklift-carrier": {
        "name": "UK hooklift prime mover and mounted module",
        "visual_lineage": "Three-axle British fire-service prime mover carrying a complete demountable pod.",
        "propulsion": "self-propelled-road",
        "reference_asset": "hazardous-materials-pod",
        "minimum_master_bbox": [165, 100],
        "minimum_reference_similarity": 0.84,
        "required_cues": [
            "complete forward cab with glazing",
            "three-axle grounded chassis",
            "visible hooklift or subframe geometry",
            "full mounted role module for every dispatched pod slot",
            "unloaded hooklift rails only on the dedicated prime-mover slot",
        ],
    },
    "ambulance-box": {
        "name": "UK ambulance conversion",
        "visual_lineage": "Box-bodied or high-roof British ambulance conversion with original, badge-free details.",
        "propulsion": "self-propelled-road",
        "reference_asset": "frontline-ambulance",
        "minimum_master_bbox": [120, 90],
        "minimum_reference_similarity": 0.78,
        "required_cues": [
            "integrated cab or high-roof van front with glazing",
            "tall clinical body volume",
            "blue-light housings at roof and front corners",
            "UK green-yellow high-visibility blocks",
            "ambulance-specific windows, doors or rear treatment",
        ],
    },
    "response-car": {
        "name": "UK response estate or fastback",
        "visual_lineage": "Contemporary British emergency estate, hatch or fastback proportions without copied grilles or badges.",
        "propulsion": "self-propelled-road",
        "reference_asset": "police-incident-response-vehicle",
        "minimum_master_bbox": [96, 48],
        "minimum_reference_similarity": 0.82,
        "required_cues": [
            "recognisable bonnet, windscreen and passenger cell",
            "separate front and rear wheel positions",
            "service-correct UK side markings",
            "physical roof or grille emergency-light fixtures",
            "role-appropriate estate, hatch or fastback stance",
        ],
    },
    "response-4x4": {
        "name": "UK emergency SUV or 4x4",
        "visual_lineage": "British operational SUV and utility 4x4 proportions with raised ride height and original detailing.",
        "propulsion": "self-propelled-road",
        "reference_asset": "coastguard-commander",
        "minimum_master_bbox": [98, 62],
        "minimum_reference_similarity": 0.78,
        "required_cues": [
            "raised ride height and robust wheel arches",
            "defined bonnet, windscreen and rear utility volume",
            "front and rear wheels grounded on one plane",
            "roof rail, rack, beacon or task equipment",
            "service-specific UK high-visibility pattern",
        ],
    },
    "operational-van": {
        "name": "UK operational van or crew carrier",
        "visual_lineage": "British panel-van, minibus or command conversion with task-specific body furniture.",
        "propulsion": "self-propelled-road",
        "reference_asset": "operational-support-van",
        "minimum_master_bbox": [112, 70],
        "minimum_reference_similarity": 0.75,
        "required_cues": [
            "complete van cab with dark glazing",
            "readable sliding-door, window or panel rhythm",
            "grounded front and rear wheel groups",
            "role-specific aerial, kennel, stowage or command equipment",
            "service-correct UK livery rather than a colour-only reskin",
        ],
    },
    "secure-police-carrier": {
        "name": "UK secure police carrier",
        "visual_lineage": "Protected police van with custody, firearms or public-order body cues.",
        "propulsion": "self-propelled-road",
        "reference_asset": "m-rav",
        "minimum_master_bbox": [120, 75],
        "minimum_reference_similarity": 0.78,
        "required_cues": [
            "complete cab and windscreen",
            "secure rear body with reduced or protected glazing",
            "heavy-duty stance and grounded wheels",
            "blue-yellow police high-visibility pattern",
            "custody, public-order or firearms role furniture",
        ],
    },
    "airport-crash-appliance": {
        "name": "UK airport crash appliance",
        "visual_lineage": "Wide, low-slung multi-axle airfield appliance with original crash-tender proportions.",
        "propulsion": "self-propelled-road",
        "reference_asset": "riv",
        "minimum_master_bbox": [140, 78],
        "minimum_reference_similarity": 0.76,
        "required_cues": [
            "wide panoramic cab",
            "large flotation tyres or heavy wheel groups",
            "low, broad tank body",
            "roof or bumper firefighting monitor",
            "airfield-scale high-visibility markings",
        ],
    },
    "airport-operations": {
        "name": "UK airfield operations vehicle",
        "visual_lineage": "High-visibility airfield command or inspection car/4x4 with operational roof equipment.",
        "propulsion": "self-propelled-road",
        "reference_asset": "airfield-operations-supervisor",
        "minimum_master_bbox": [96, 60],
        "minimum_reference_similarity": 0.76,
        "required_cues": [
            "car or SUV passenger-cell proportions",
            "amber operational light fixture",
            "high-visibility airfield checker or block treatment",
            "defined front structure and grounded wheels",
            "command, inspection or firefighting-supervisor equipment",
        ],
    },
    "recovery-platform": {
        "name": "UK recovery and engineering platform",
        "visual_lineage": "British roadside recovery platform from light slide-bed to heavy multi-axle wrecker.",
        "propulsion": "self-propelled-road",
        "reference_asset": "hgv-recovery-vehicle",
        "minimum_master_bbox": [130, 75],
        "minimum_reference_similarity": 0.72,
        "required_cues": [
            "complete commercial cab",
            "grounded wheel groups matched to payload class",
            "visible recovery bed, boom, winch or underlift",
            "amber warning-light fixtures",
            "working-deck geometry distinct from a closed equipment body",
        ],
    },
    "towed-equipment": {
        "name": "UK towed specialist equipment",
        "visual_lineage": "Purpose-built British trailer, boat trailer or mobile equipment unit.",
        "propulsion": "towed-road",
        "reference_asset": "boat-trailer",
        "minimum_master_bbox": [94, 38],
        "minimum_reference_similarity": 0.68,
        "required_cues": [
            "visible drawbar, hitch or towing frame",
            "one or more grounded trailer wheel groups",
            "role-specific carried equipment",
            "stable direction-neutral three-quarter presentation",
            "no false powered cab unless a tow vehicle is part of the sprite",
        ],
    },
    "rotorcraft": {
        "name": "UK emergency rotorcraft",
        "visual_lineage": "Light police/medical or medium SAR helicopter with readable aircraft-specific geometry.",
        "propulsion": "rotorcraft",
        "reference_asset": "coastguard-rescue-helicopter-large",
        "minimum_master_bbox": [175, 80],
        "minimum_reference_similarity": 0.72,
        "required_cues": [
            "cockpit glazing and fuselage volume",
            "main rotor disc with correct hub placement",
            "tail boom and tail-rotor relationship",
            "landing gear or skids",
            "service-specific but logo-free UK livery",
        ],
    },
    "rescue-watercraft": {
        "name": "UK rescue watercraft",
        "visual_lineage": "Inshore or all-weather British rescue craft with hull, cabin and marine equipment cues.",
        "propulsion": "watercraft",
        "reference_asset": "alb",
        "minimum_master_bbox": [105, 55],
        "minimum_reference_similarity": 0.66,
        "required_cues": [
            "recognisable hull sheer and bow",
            "cabin, console or crew position",
            "marine rails, aerials or rescue equipment",
            "waterline or wake treatment that does not imply a road chassis",
            "inshore or all-weather scale relationship",
        ],
    },
    "cycle-response": {
        "name": "UK cycle response unit",
        "visual_lineage": "Emergency-service bicycle with panniers and rider/task equipment readable at map scale.",
        "propulsion": "cycle",
        "reference_asset": "medical-cycle-responder",
        "minimum_master_bbox": [70, 60],
        "minimum_reference_similarity": 0.90,
        "required_cues": [
            "two separate bicycle wheels",
            "frame and handlebar structure",
            "medical panniers or response equipment",
            "high-visibility responder treatment",
            "compact physical emergency-light fixture where fitted",
        ],
    },
    "specialist-transporter": {
        "name": "UK specialist transporter",
        "visual_lineage": "Powered carrier whose transported load defines the operational role.",
        "propulsion": "self-propelled-road",
        "reference_asset": "atv-carrier",
        "minimum_master_bbox": [115, 72],
        "minimum_reference_similarity": 0.66,
        "required_cues": [
            "complete powered cab or towing unit",
            "grounded carrier wheel groups",
            "clearly mounted ATV, hovercraft, livestock body or stair assembly",
            "load-restraint, platform or deployment hardware",
            "silhouette materially different from a closed panel van",
        ],
    },
    "eod-heavy": {
        "name": "UK heavy EOD equipment vehicle",
        "visual_lineage": "Heavy bomb-disposal equipment platform with protected stowage and deployment hardware.",
        "propulsion": "self-propelled-road",
        "reference_asset": "eod-heavy-equipment-vehicle",
        "minimum_master_bbox": [175, 90],
        "minimum_reference_similarity": 0.90,
        "required_cues": [
            "complete heavy commercial cab",
            "multi-axle grounded chassis",
            "large secure equipment body",
            "robot, containment or deployment-compartment cues",
            "EOD high-visibility treatment without military insignia",
        ],
    },
}


# The second value is the role-specific silhouette/equipment brief.  It is not
# a caption: a recolour alone does not fulfil it.
ASSIGNMENTS: dict[str, tuple[str, str]] = {
    "fire-rescue-pump": ("forward-control-fire", "urban water-ladder body with roller shutters and roof ladder gantry"),
    "light-4x4-pump": ("response-4x4", "compact off-road pump body with hose lockers and raised 4x4 stance"),
    "aerial-appliance": ("aerial-fire", "long multi-axle aerial platform with boom, basket and stabilisers"),
    "fire-officer": ("response-car", "fire-command estate or hatch with roof bar and command identification panel"),
    "rescue-support-unit": ("specialist-emergency-hgv", "deep-locker rescue body with crane, winch or technical-rescue roof equipment"),
    "frontline-ambulance": ("ambulance-box", "frontline emergency ambulance with tall patient box and corner blue-light housings"),
    "water-carrier": ("specialist-emergency-hgv", "large cylindrical or faceted water tank with fill and delivery hardware"),
    "hazmat-unit": ("specialist-emergency-hgv", "sealed hazardous-materials equipment body with decontamination stowage"),
    "police-incident-response-vehicle": ("response-car", "marked police response estate or hatch with full roof lightbar"),
    "hems": ("rotorcraft", "compact air-ambulance helicopter with medical-service cabin treatment"),
    "rapid-response-vehicle": ("response-car", "ambulance rapid-response estate or hatch with green-yellow side blocks"),
    "police-helicopter": ("rotorcraft", "light police observation helicopter with sensor turret and compact cabin"),
    "dog-support-unit": ("operational-van", "police dog van with ventilated kennel body and reduced rear glazing"),
    "armed-response-vehicle": ("response-car", "high-performance police estate or SUV-like fastback with firearms stowage cues"),
    "breathing-apparatus-support-unit": ("specialist-emergency-hgv", "cylinder-support body with breathing-apparatus locker rhythm and refill equipment"),
    "incident-command-control-unit": ("specialist-emergency-hgv", "expanded command body with aerial mast, awning and communications roofline"),
    "rescue-pump": ("forward-control-fire", "rescue-pump locker body with roof ladder and technical-rescue equipment"),
    "carp": ("specialist-emergency-hgv", "combined aerial-rescue pump body with elevated access equipment"),
    "co-responder-vehicle": ("response-car", "joint-service response car with visibly mixed emergency-service livery cues"),
    "joint-response-unit": ("response-car", "joint police-medical response estate with dual-role markings and equipment load"),
    "otl": ("response-car", "operational team-leader estate with command light and reduced frontline markings"),
    "general-practitioner": ("response-car", "doctor response estate with medical high-visibility panels and compact blue lights"),
    "community-first-responder": ("response-car", "community medical response hatch with restrained blue-light installation"),
    "crew-carrier": ("operational-van", "windowed emergency-service minibus with multiple passenger rows"),
    "traffic-car": ("response-car", "roads-policing estate with high-visibility rear and motorway equipment stance"),
    "armed-traffic-car": ("response-car", "roads-policing firearms estate with heavier equipment load and distinct roof fixture"),
    "heavy-4x4-tanker": ("specialist-emergency-hgv", "high-clearance multi-axle water tanker with off-road tyres and tank body"),
    "prv": ("response-4x4", "paramedic response SUV with clinical equipment load and raised utility stance"),
    "srv": ("operational-van", "specialist response van with equipment cabinets and task-specific roof furniture"),
    "welfare-vehicle": ("operational-van", "crew welfare van with awning, service windows or welfare body fittings"),
    "atv-carrier": ("specialist-transporter", "flat or beavertail carrier with a visibly secured all-terrain vehicle"),
    "ambulance-control-unit": ("specialist-emergency-hgv", "large ambulance command body with mast, awning and control-room windows"),
    "cbrn-vehicle": ("operational-van", "CBRN response van with sealed equipment stowage and decontamination cues"),
    "mass-casualty-equipment": ("specialist-emergency-hgv", "high-volume mass-casualty stores body with deployment-side lockers"),
    "ambulance-officer": ("response-car", "ambulance officer estate with command markings and roof lightbar"),
    "bfu": ("specialist-emergency-hgv", "bulk-foam unit with large tank, foam plumbing and heavy appliance chassis"),
    "f-wrc": ("specialist-emergency-hgv", "foam-and-water carrier with dual-medium tank and delivery hardware"),
    "wrl-cafs": ("forward-control-fire", "water-ladder CAFS appliance with foam-system locker and roof ladder"),
    "rp-cafs": ("forward-control-fire", "rescue-pump CAFS appliance with rescue lockers and compressed-air foam cues"),
    "osu": ("specialist-emergency-hgv", "operational support unit with extended locker body and deployment equipment"),
    "pm": ("hooklift-carrier", "unloaded three-axle prime mover with exposed hooklift rails"),
    "water-pod": ("hooklift-carrier", "mounted water tank pod with fill, vent and delivery fittings"),
    "bulk-foam-pod": ("hooklift-carrier", "mounted bulk-foam tank pod with foam plumbing and identification panels"),
    "rescue-pod": ("hooklift-carrier", "mounted technical-rescue pod with deep roller-shutter lockers"),
    "command-pod": ("hooklift-carrier", "mounted command pod with windows, awning and communications mast"),
    "welfare-pod": ("hooklift-carrier", "mounted welfare pod with windows, awning and crew-support fittings"),
    "basu-pod": ("hooklift-carrier", "mounted breathing-apparatus pod with cylinder-bank locker cues"),
    "misting-pod": ("hooklift-carrier", "mounted high-pressure misting pod with hose reels and compact tank"),
    "hazardous-materials-pod": ("hooklift-carrier", "mounted hazardous-materials pod with sealed lockers and decontamination cues"),
    "osu-pod": ("hooklift-carrier", "mounted operational-support pod with deployment-side equipment lockers"),
    "hvp": ("hooklift-carrier", "mounted high-volume pump module with large hose runs and pump hardware"),
    "psu-carrier": ("operational-van", "public-order personnel carrier with protected windows and equipment compartment"),
    "firearms-personnel-carrier": ("secure-police-carrier", "firearms team carrier with secure rear cabin and weapons-equipment stowage"),
    "multiple-dog-carrier": ("operational-van", "extended dog carrier with multiple ventilated kennel compartments"),
    "detention-van": ("secure-police-carrier", "custody van with protected cell body and limited rear glazing"),
    "mounted-unit": ("specialist-transporter", "powered horsebox with ventilated livestock body and access ramp"),
    "m-rav": ("secure-police-carrier", "protected multi-role armoured van with reinforced body and reduced glazing"),
    "crv": ("response-car", "compact police command response vehicle with command lighting and equipment load"),
    "coastguard-mud-rescue-unit": ("operational-van", "coastguard van with mud-rescue sled, boards and decontamination stowage"),
    "coastguard-rope-rescue-unit": ("operational-van", "coastguard rope-rescue van with high-angle equipment and roof rack"),
    "coastguard-commander": ("response-4x4", "coastguard command SUV with roof rack, amber-blue lighting and command markings"),
    "flood-rescue-unit-trailer": ("towed-equipment", "enclosed flood-rescue trailer with drawbar and water-rescue equipment"),
    "mud-decontamination-unit": ("operational-van", "decontamination van with wash-down equipment and sealed stores body"),
    "support-unit": ("operational-van", "coastguard or rescue support van with mixed crew and equipment body"),
    "coastguard-rescue-helicopter": ("rotorcraft", "medium SAR helicopter with winch, high cabin and coastguard livery"),
    "coastguard-rescue-helicopter-large": ("rotorcraft", "large SAR helicopter with extended cabin, winch and heavy landing gear"),
    "4x4-vehicle": ("response-4x4", "general rescue 4x4 with raised stance, roof rack and recovery equipment"),
    "inland-rescue-boat-trailer": ("towed-equipment", "rigid rescue boat on a braked drawbar trailer"),
    "ilb": ("rescue-watercraft", "small inshore lifeboat with open or compact-console crew layout"),
    "alb": ("rescue-watercraft", "large all-weather lifeboat with enclosed wheelhouse and deep hull"),
    "rescue-watercraft-trailer": ("towed-equipment", "personal rescue watercraft on a compact launch trailer"),
    "hovercraft-trailer": ("towed-equipment", "rescue hovercraft secured on a wide low launch trailer"),
    "hovercraft-transporter": ("specialist-transporter", "powered transporter with a clearly mounted rescue hovercraft"),
    "light-4x4": ("response-4x4", "light rescue 4x4 with short body, high clearance and compact roof equipment"),
    "boat-trailer": ("towed-equipment", "general rescue boat with hull supports, drawbar and launch wheels"),
    "major-foam-tender": ("airport-crash-appliance", "large multi-axle foam tender with broad tank body and roof monitor"),
    "riv": ("airport-crash-appliance", "rapid-intervention crash appliance with low wide body and roof turret"),
    "airfield-firefighting-command-vehicle": ("airport-operations", "airfield fire command SUV with command roof equipment and chequered livery"),
    "rescue-stairs": ("specialist-transporter", "powered airfield rescue stair vehicle with elevated stair assembly"),
    "airfield-operations-vehicle": ("airport-operations", "airfield inspection estate or hatch with amber bar and checker markings"),
    "airfield-operations-supervisor": ("airport-operations", "airfield supervisor SUV with amber lightbar and command equipment"),
    "medical-equipment-trailer": ("towed-equipment", "compact enclosed medical stores trailer with drawbar and side access"),
    "armed-cell-van": ("secure-police-carrier", "armed custody van with protected cell body and firearms-team equipment"),
    "medical-cycle-responder": ("cycle-response", "medical response bicycle with panniers, responder kit and compact blue lights"),
    "pump-trailer": ("towed-equipment", "compact pump trailer with visible engine, hose connections and drawbar"),
    "control-van-sar": ("operational-van", "SAR command van with mast, awning and control-room glazing"),
    "operational-support-van": ("operational-van", "SAR support van with equipment lockers, roof rack and scene-lighting mast"),
    "operational-support-trailer": ("towed-equipment", "enclosed operational-support trailer with deployment-side access and equipment stowage"),
    "sar-flood-rescue-trailer": ("towed-equipment", "flood-rescue trailer carrying dry suits, boards and water equipment"),
    "drone-vehicle-sar-hq": ("operational-van", "SAR drone van with roof aerials, launch cases and control-workstation body"),
    "drone-vehicle-fire-station": ("operational-van", "fire drone vehicle with roof aerials and compact equipment compartment"),
    "drone-vehicle-police-station": ("operational-van", "police drone vehicle with surveillance mast and equipment cases"),
    "personal-sar-vehicle": ("response-car", "personal SAR response estate with restrained markings and rescue kit"),
    "sar-4x4": ("response-4x4", "SAR utility 4x4 with roof rack, recovery points and high-visibility panels"),
    "rrv-2": ("response-car", "second ambulance rapid-response estate family with distinct body and light installation"),
    "community-midwife": ("response-car", "community midwife response hatch or estate with subtle medical markings"),
    "specialist-paramedic-rrv": ("response-car", "specialist paramedic estate with advanced-clinical equipment load"),
    "patient-transport-service-ambulance": ("ambulance-box", "patient-transport high-roof van with accessible side or rear door cues"),
    "critical-care-transfer-ambulance": ("ambulance-box", "critical-care box ambulance with larger clinical body and intensive-care equipment cues"),
    "mountain-rescue-4x4": ("response-4x4", "mountain-rescue 4x4 with off-road tyres, roof rack and rope equipment"),
    "control-van-mountain-rescue": ("operational-van", "mountain-rescue command van with mast, awning and control workspace"),
    "search-dog-unit": ("operational-van", "police search-dog van with ventilated kennel compartment"),
    "search-dog-unit-sar": ("operational-van", "SAR search-dog van with kennel ventilation and rescue equipment rack"),
    "crew-carrier-sar": ("operational-van", "windowed SAR crew van with passenger rows and rear equipment bay"),
    "recovery-vehicle": ("recovery-platform", "light recovery truck with winch, towing gear and open working deck"),
    "flatbed-recovery-vehicle": ("recovery-platform", "slide-bed recovery truck with long open loading platform"),
    "hgv-recovery-vehicle": ("recovery-platform", "heavy multi-axle wrecker with boom, underlift and stabilisers"),
    "rru": ("specialist-emergency-hgv", "rail response unit with heavy equipment body and trackside deployment gear"),
    "eiu": ("response-4x4", "EOD equipment inspection SUV with protected cases and command-light fit"),
    "eod-commander": ("response-4x4", "EOD command SUV with communications equipment and command markings"),
    "eod-response-vehicle": ("response-4x4", "EOD response utility vehicle with protected equipment bay"),
    "eod-medium-equipment-van": ("operational-van", "medium EOD van with secure rear equipment compartments"),
    "eod-heavy-equipment-vehicle": ("eod-heavy", "heavy EOD truck with large secure body and robot-deployment compartment"),
    "marine-eod-response-vehicle": ("response-4x4", "marine EOD response 4x4 with dive and shoreline equipment"),
    "marine-eod-equipment-van": ("operational-van", "marine EOD van with dive, sonar and containment-equipment stowage"),
    "welfare-vehicle-2": ("operational-van", "second welfare conversion with awning, service hatch and crew facilities"),
    "cell-van": ("secure-police-carrier", "standard custody van with protected cell body and reduced rear glazing"),
}


FORBIDDEN_SHORTCUTS = (
    "container or trailer presented as a self-propelled dispatched vehicle",
    "colour-only reskin used to imply a different vehicle family",
    "copied manufacturer badge, grille, fleet number or protected service crest",
    "light bloom used to hide an unreadable cab or role body",
    "detail that disappears at native 110 px map scale",
)
